### ISSUE TITLE
Doesn't run on Java 8

### ISSUE THREAD

**Issue by Captain-Chaos** [grails-samples/grails-petclinic#14]
I can't run the petclinic example with Java 8 on Linux; it fails to start with the following error:

```
| Error Compilation error: startup failed:
/home/pepijn/Projects/Grails/grails-petclinic-master/target/work/plugins/database-migration-1.4.0/grails-app/controllers/grails/plugin/databasemigration/DbdocController.groovy: -1: Repetitive method name/signature for method 'java.lang.Object withFormat(groovy.lang.Closure)' in class 'grails.plugin.databasemigration.DbdocController'.
 @ line -1, column -1.
/home/pepijn/Projects/Grails/grails-petclinic-master/target/work/plugins/database-migration-1.4.0/grails-app/controllers/grails/plugin/databasemigration/DbdocController.groovy: -1: Repetitive method name/signature for method 'java.lang.Object withFormat(groovy.lang.Closure)' in class 'grails.plugin.databasemigration.DbdocController'.
 @ line -1, column -1.
2 errors
```

uname -a:
Linux falcon 3.13.0-27-generic #50-Ubuntu SMP Thu May 15 18:06:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

java -version:
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

When I change JAVA_HOME to Java 7, it does work, so it must be some incompatibility with Java 8.

**Comment by graemerocher** [comment]
closing this as the Grails 3.0 versions runs fine on Java 8
